version: '3.8'

services:
  mc:
    container_name: mc
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: 'TRUE'
      TYPE: 'FORGE'
      VERSION: '1.20.1'
    network_mode: host
    volumes:
      - ./tmp:/data
