spring:
  profiles:
    active: 'langchain,sqlite'

  web:
    resources:
      static-locations:
        - 'classpath:/static/'
        - 'classpath:/neighbors/'
logging:
  level:
    dev:
      langchain4j:
        model:
          mistralai: DEBUG
